set -o vi

function txt2pdf {
  cupsfilter "$1" > "$2"
}

EDITOR="vim"
SHELL="/usr/local/bin/bash"
HISTFILESIZE=
HISTSIZE=
GPG_TTY="$(tty)"

export EDITOR
export SHELL
export HISTFILESIZE
export HISTSIZE
export GPG_TTY

alias vi="vim"
alias l="ls"
alias sl="ls"
alias s="ls"
alias md="open -a /Applications/MacDown.app/"
alias grep="grep --color=auto --exclude-dir=.git --exclude-dir=target --exclude-dir=.idea"
alias egrep="egrep --color=auto --exclude-dir=.git --exclude-dir=target --exclude-dir=.idea"
alias grepc="grep --color=always --exclude-dir=.git --exclude-dir=target --exclude-dir=.idea"
alias egrepc="egrep --color=always --exclude-dir=.git --exclude-dir=target --exclude-dir=.idea"

alias pself="ps -Ao flags,state,user,pid,ppid,%cpu,pri,nice,paddr,rss,wchan,start,tty,time,command | sort -n -k4"
alias gitk="gitk 2> /dev/null"

alias cdpr="cd ~/projects"
alias cdpo="cd ~/projects/potetm"
alias cdbl="cd ~/projects/potetm/potetm.github.io"
alias cdconf="cd ~/projects/potetm/config"
alias cdti="cd ~/projects/potetm/tire-iron"
alias cdj="cd ~/projects/potetm/journal"
alias cdt="cd ~/Dropbox/thoughts"
alias cdj="cd ~/projects/potetm/journal"

alias dnsflush="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder"

complete -C aws_completer aws
complete -o nospace -d cd

alias speed-test="wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip"
alias reset-cam="sudo killall VDCAssistant"

function copr {
  local -r pr="$1"
  local -r branch="$2"

  if [[ -z $pr ]] || [[ -z $branch ]]; then
    cat << DONE >&2
Usage: $(basename "$0") pr-num checkout-branch

pr-num          - The number of the pr
checkout-branch - The branch you wish to check out to
DONE
    return 1
  fi
  git fetch upstream "pull/$pr/head:$branch" && \
  git checkout "$branch"
}

if [[ -f ~/.secrets ]]; then
  source ~/.secrets
fi
