set -o vi
export EDITOR="vim"
export GREP_OPTIONS="--color=auto --exclude-dir=.git --exclude-dir=target"

alias f="fg"

alias vi="vim"
alias l="ls"
alias sl="ls"
alias s="ls"

alias pself="ps -Ao flags,state,user,pid,ppid,%cpu,pri,nice,paddr,rss,wchan,start,tty,time,command | sort -n -k4"
alias gitk="gitk 2> /dev/null"

alias cdpr="cd ~/projects"
alias cdbl="cd ~/projects/potetm/potetm.github.io"
alias cdba="cd ~/projects/potetm/clobaconjure"
alias cdbacon="cd ~/projects/baconjs/bacon.js"
alias cdm="cd ~/projects/cicayda/monolith"
alias cdsys="cd ~/projects/cicayda/SysOps"
alias cdev="cd ~/projects/cicayda/devops"
alias cdconf="cd ~/projects/potetm/config"

alias dnsflush="sudo killall -HUP mDNSResponder"
